### ISSUE TITLE
If I want to train a 48k vocos vocoder, what config should I modify?

### ISSUE THREAD

**Issue by splinter21** [charactr-platform/vocos#3]
And another question, I notice that in the paper you said "the replacement of ResBlocks with ConvNeXt further improves performance.", I want to know how much performance has ConvNeXt version improved compared to ResBlock1 (HIFIGANv1) version?

Thanks!

**Comment by hubertsiuzdak** [comment]
I'd suggest you start with the [configs/vocos.yaml](https://github.com/charactr-platform/vocos/blob/03c4fcbb321e4b04dd9b5091486eedabf1dc9de0/configs/vocos.yaml) file, and adjust the `sample_rate`, `num_samples` and STFT parameters as follows:

```
data:
  class_path: vocos.dataset.VocosDataModule
  init_args:
    train_params:
      sampling_rate: 48000
      num_samples: 32768 

    val_params:
      sampling_rate: 48000
      num_samples: 96768

model:
  class_path: vocos.experiment.VocosExp
  init_args:
    sample_rate: 48000
    mrd_loss_coeff: 1.0

    feature_extractor:
      class_path: vocos.feature_extractors.MelSpectrogramFeatures
      init_args:
        sample_rate: 48000
        n_fft: 2048
        hop_length: 512

    head:
      class_path: vocos.heads.ISTFTHead
      init_args:
        n_fft: 2048
        hop_length: 512
``` 
Also, you might want to set the `mrd_loss_coeff` to 1.0 right from the start. In my experience, it does slow down the convergence in terms of the UTMOS score a bit, but it's key for reducing the buzziness in the audio output. Now it makes me think that UTMOS might not be the best proxy to evaluate the perceptual quality.
